import { Roboto } from "next/font/google";
import "./globals.css";
import Headers from "./components/layouts/Header";

const roboto = Roboto({ subsets: ["latin"], weight:['100', '300', '500', '700'] });

export const metadata = {
  title: "Food Order",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="">
          <Headers />
          
            {children}
         
          <footer className="border-t p-8 text-center">
            &copy; 2023 All right reserved
          </footer>
        </main>
      </body>
    </html>
  );
}
